[package]
name = "stock-analysis-api"
version = "0.1.0"
authors = ["huud-e <huud.duu@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.0.0"
actix-rt = "1.0.0"
serde = {version = "1.0.104", features = ["derive"]}
dotenv = "0.15.0"
config = "0.10.1"